// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><title>LockeIn</title><meta charset=\"UTF-8\"><script src=\"/assets/htmx.min.js\"></script><script src=\"/assets/_hyperscript.min.js\"></script><link rel=\"stylesheet\" href=\"/assets/style.css\"><link rel=\"icon\" href=\"/assets/favicon.ico\"></head><body hx-boost=\"true\"><h1>LockeIn</h1><div id=\"app\"><form action=\"/goal\" method=\"post\" hx-post=\"/goal\" hx-target=\"#app\" hx-push-url=\"true\"><label for=\"name\">Achieve this:</label> <input type=\"text\" id=\"name\" name=\"name\"> <label for=\"deadline\">By then:</label> <input type=\"datetime-local\" id=\"deadline\" name=\"endDate\" value=\"2024-10-27T22:45\"> <input type=\"submit\" value=\"Submit\"></form></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
